from sqlalchemy import Column, Integer, String, BigInteger, Float, Date, Text
from config.database import Base


class db_auditsa_tv(Base):
    __tablename__ = "auditsa_api_tv"
    __table_args__ = {"schema": "public"}

    id = Column(Integer, autoincrement=True, primary_key=True)
    Fecha = Column(Date)
    IdPlaza = Column(Integer)
    Plaza = Column(String(255))
    IdLocalidad = Column(Integer)
    Localidad = Column(String(255))
    IdMedio = Column(Integer)
    Medio = Column(String(255))
    IdTipoMedio = Column(Integer)
    TipoMedio = Column(String(255))
    IdCanal = Column(Integer)
    Canal = Column(String(255))
    HInicio = Column(String(50))
    HFinal = Column(String(50))
    IdMarca = Column(Integer)
    Marca = Column(String(255))
    IdSubmarca = Column(Integer)
    Submarca = Column(String(255))
    IdProducto = Column(Integer)
    Producto = Column(String(255))
    IdVersion = Column(BigInteger)
    Version = Column(Text)
    DReal = Column(Integer)
    DTeorica = Column(Integer)
    IdTipoSpot = Column(Integer)
    TipoSpot = Column(String(255))
    IdSubTipoSpot = Column(Integer)
    SubTipoSpot = Column(String(255))
    IdTipoCorte = Column(Integer)
    TipoCorte = Column(String(255))
    NoCorte = Column(Integer)
    PEnCorte = Column(String(255))
    IdCampania = Column(Integer)
    Campania = Column(String(255))
    IdCorporativo = Column(Integer)
    Corporativo = Column(String(255))
    IdAnunciante = Column(Integer)
    Anunciante = Column(String(255))
    IdAgenciaP = Column(Integer)
    AgenciaP = Column(String(255))
    IdCentralMedios = Column(Integer)
    CentralMedios = Column(String(255))
    IdIndustria = Column(Integer)
    Industria = Column(String(255))
    IdMercado = Column(Integer)
    Mercado = Column(String(255))
    IdSegmento = Column(Integer)
    Segmento = Column(String(255))
    IdDeteccion = Column(BigInteger)
    Tarifa = Column(Float)
    Testigo = Column(Text)
    IdPrograma = Column(Integer)
    Programa = Column(String(255))
    Subtitulo = Column(Text)
    IdGenero = Column(Integer)
    Genero = Column(String(255))
    FHoraria = Column(String(255))
    GComercial = Column(String(255))
    GEstacion = Column(String(255))
    Origen = Column(String(255))
    VerCodigo = Column(String(255))
