from sqlalchemy import Column, Integer, BigInteger, Float, Date, Unicode, UnicodeText

from config.database import SqlServerBase


class ss_auditsa_tv(SqlServerBase):
    __tablename__ = "auditsa_api_tv"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    Fecha = Column(Date)
    IdPlaza = Column(Integer)
    Plaza = Column(Unicode(255))
    IdLocalidad = Column(Integer)
    Localidad = Column(Unicode(255))
    IdMedio = Column(Integer)
    Medio = Column(Unicode(255))
    IdTipoMedio = Column(Integer)
    TipoMedio = Column(Unicode(255))
    IdCanal = Column(Integer)
    Canal = Column(Unicode(255))
    HInicio = Column(Unicode(50))
    HFinal = Column(Unicode(50))
    IdMarca = Column(Integer)
    Marca = Column(Unicode(255))
    IdSubmarca = Column(Integer)
    Submarca = Column(Unicode(255))
    IdProducto = Column(Integer)
    Producto = Column(Unicode(255))
    IdVersion = Column(BigInteger)
    Version = Column(UnicodeText)
    DReal = Column(Integer)
    DTeorica = Column(Integer)
    IdTipoSpot = Column(Integer)
    TipoSpot = Column(Unicode(255))
    IdSubTipoSpot = Column(Integer)
    SubTipoSpot = Column(Unicode(255))
    IdTipoCorte = Column(Integer)
    TipoCorte = Column(Unicode(255))
    NoCorte = Column(Integer)
    PEnCorte = Column(Unicode(255))
    IdCampania = Column(Integer)
    Campania = Column(Unicode(255))
    IdCorporativo = Column(Integer)
    Corporativo = Column(Unicode(255))
    IdAnunciante = Column(Integer)
    Anunciante = Column(Unicode(255))
    IdAgenciaP = Column(Integer)
    AgenciaP = Column(Unicode(255))
    IdCentralMedios = Column(Integer)
    CentralMedios = Column(Unicode(255))
    IdIndustria = Column(Integer)
    Industria = Column(Unicode(255))
    IdMercado = Column(Integer)
    Mercado = Column(Unicode(255))
    IdSegmento = Column(Integer)
    Segmento = Column(Unicode(255))
    IdDeteccion = Column(BigInteger)
    Tarifa = Column(Float)
    Testigo = Column(UnicodeText)
    IdPrograma = Column(Integer)
    Programa = Column(Unicode(255))
    Subtitulo = Column(UnicodeText)
    IdGenero = Column(Integer)
    Genero = Column(Unicode(255))
    FHoraria = Column(Unicode(255))
    GComercial = Column(Unicode(255))
    GEstacion = Column(Unicode(255))
    Origen = Column(Unicode(255))
    VerCodigo = Column(Unicode(255))


class ss_auditsa_radio(SqlServerBase):
    __tablename__ = "auditsa_api_radio"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    Fecha = Column(Date)
    IdPlaza = Column(Integer)
    Plaza = Column(Unicode(255))
    IdLocalidad = Column(Integer)
    Localidad = Column(Unicode(255))
    IdMedio = Column(Integer)
    Medio = Column(Unicode(255))
    IdTipoMedio = Column(Integer)
    TipoMedio = Column(Unicode(255))
    IdCanal = Column(Integer)
    Canal = Column(Unicode(255))
    HInicio = Column(Unicode(50))
    HFinal = Column(Unicode(50))
    IdMarca = Column(Integer)
    Marca = Column(Unicode(255))
    IdSubmarca = Column(Integer)
    Submarca = Column(Unicode(255))
    IdProducto = Column(Integer)
    Producto = Column(Unicode(255))
    IdVersion = Column(BigInteger)
    Version = Column(UnicodeText)
    DReal = Column(Integer)
    DTeorica = Column(Integer)
    IdTipoSpot = Column(Integer)
    TipoSpot = Column(Unicode(255))
    IdSubTipoSpot = Column(Integer)
    SubTipoSpot = Column(Unicode(255))
    IdTipoCorte = Column(Integer)
    TipoCorte = Column(Unicode(255))
    NoCorte = Column(Integer)
    PEnCorte = Column(Unicode(255))
    IdCampania = Column(Integer)
    Campania = Column(Unicode(255))
    IdCorporativo = Column(Integer)
    Corporativo = Column(Unicode(255))
    IdAnunciante = Column(Integer)
    Anunciante = Column(Unicode(255))
    IdAgenciaP = Column(Integer)
    AgenciaP = Column(Unicode(255))
    IdCentralMedios = Column(Integer)
    CentralMedios = Column(Unicode(255))
    IdIndustria = Column(Integer)
    Industria = Column(Unicode(255))
    IdMercado = Column(Integer)
    Mercado = Column(Unicode(255))
    IdSegmento = Column(Integer)
    Segmento = Column(Unicode(255))
    IdDeteccion = Column(BigInteger)
    Tarifa = Column(Float)
    Testigo = Column(UnicodeText)
    IdPrograma = Column(Integer)
    Programa = Column(Unicode(255))
    Subtitulo = Column(UnicodeText, server_default=u"N.A.")
    IdGenero = Column(Integer)
    Genero = Column(Unicode(255))
    FHoraria = Column(Unicode(255))
    GComercial = Column(Unicode(255))
    GEstacion = Column(Unicode(255))
    Origen = Column(Unicode(255))
    VerCodigo = Column(Unicode(255))


class ss_auditsa_media_master_totals(SqlServerBase):
    __tablename__ = "auditsa_api_media_master_totals"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    FechaInicio = Column(Date)
    FechaFin = Column(Date)
    Periodo = Column(Unicode(100))
    Medio = Column(Unicode(128))
    Canal = Column(Unicode(255))
    GEstacion = Column(Unicode(255))
    FHoraria = Column(Unicode(100))
    NoCorte = Column(Integer)
    TipoSpot = Column(Unicode(255))
    Genero = Column(Unicode(255))
    TipoMaster = Column(Unicode(128))
    IdMaster = Column(BigInteger)
    Version = Column(UnicodeText)
    Anunciante = Column(Unicode(255))
    Marca = Column(Unicode(255))
    Submarca = Column(Unicode(255))
    Producto = Column(Unicode(255))
    Segmento = Column(Unicode(255))
    Industria = Column(Unicode(255))
    Mercado = Column(Unicode(255))
    DTeorica = Column(Integer)
    TotalHit = Column(Integer)
    TotalInversion = Column(Float)
    Testigo = Column(UnicodeText, server_default=u"N.A.")


class ss_auditsa_media_master_library(SqlServerBase):
    __tablename__ = "auditsa_api_media_master_library"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    IdMaster = Column(BigInteger)
    TipoMaster = Column(Unicode(128))
    Version = Column(UnicodeText)
    Anunciante = Column(Unicode(255))
    Marca = Column(Unicode(255))
    Submarca = Column(Unicode(255))
    Producto = Column(Unicode(255))
    Segmento = Column(Unicode(255))
    Industria = Column(Unicode(255))
    Mercado = Column(Unicode(255))
    DTeorica = Column(Integer)
    Testigo = Column(UnicodeText, server_default=u"N.A.")


class ss_auditsa_impresos(SqlServerBase):
    __tablename__ = "auditsa_api_impresos"
    __table_args__ = {"schema": "dbo"}

    id = Column(Integer, primary_key=True, autoincrement=True)
    IdMedio = Column(Integer)
    Medio = Column(Unicode(128))
    IdFuente = Column(Integer, server_default="0")
    Fuente = Column(Unicode(128))
    Autor = Column(Unicode(128))
    Seccion = Column(Unicode(128))
    Pagina = Column(Unicode(128))
    Tiraje = Column(BigInteger)
    Costo = Column(Float)
    Fecha = Column(Date)
    Testigo = Column(UnicodeText, server_default=u"N.A.")
    Anunciante = Column(Unicode(128))
    Marca = Column(Unicode(128))
    Submarca = Column(Unicode(128))
    Producto = Column(Unicode(128))
    Sector = Column(Unicode(128))
    Subsector = Column(Unicode(128))
    Categoria = Column(Unicode(128))
    Dimension = Column(Float)
    TextoNota = Column(UnicodeText, server_default=u"N.A.")
